### ISSUE TITLE
Specify layout

### ISSUE THREAD

**Issue by Weasy666** [mvlabat/bevy_megaui#2]
Is it possible to specify that the label of an inputfield is on the left? And also that two buttons or an inputfield and a button are on the same line?

**Comment by vladbat00** [comment]
Hi!

I believe this is a question about the API of `megaui` itself. Since `bevy_megaui` is just a plugin that implements rendering `megaui` widgets and re-exports the whole `megaui` crate as a module, the related features aren't affected by `bevy_megaui`.
So, regarding the questions themselves, I'll try to answer them, but keep in mind that I'm not an author of `megaui` and I'm quite new to it as well.

> Is it possible to specify that the label of an inputfield is on the left?

As far as I know, this is not possible.

> And also that two buttons or an inputfield and a button are on the same line?

I think your best call is to position them manually. You might also find groups useful if you need to draw multiple lines that way. See https://github.com/not-fl3/macroquad/blob/6d6f74ae6e87f8c2dcd777575838b2d5b28f0504/examples/ui.rs#L161

In case you want to submit a feature request, I suggest to do so in the [megaui repo](https://github.com/not-fl3/megaui). Or if you have any other questions about the megaui API, feel free to join miniquad's discord (there's a channel about `megaui`): https://discord.gg/d78Na5YC.

**Comment by Weasy666** [comment]
Thank you for the answer and for pointing me into the right direction!
